CL to demonstrate the infeasibility of using namespace
... to make *.microdroid modules hidden from Make

This CL fails with the following error:

error: system/core/init/microdroid/Android.bp:13:1: module
"libinit.microdroid" variant "android_arm64_armv8-a_static": module
source path "system/core/init/microdroid/action.cpp" does not exist
error: system/core/init/microdroid/Android.bp:13:1: module
"libinit.microdroid" variant "android_arm64_armv8-a_static": module
source path "system/core/init/microdroid/action_manager.cpp" does not
exist
<and many more>

Test: m nothing
Bug: 338160898
Change-Id: Ie6685fbb9cd1939256b0f505fc0ee549701ca39c