Update patch set 1
Patch Set 1:

hi Bowgo,

The following suggestion is good, but this will cause build errors related to functions in "libavb/avb_sysdeps_posix.c".
cosnt AvbFooter* footer = reinterpret_cast<const AvbFooter*>(
        x.data() + buf->sz - AVB_FOOTER_SIZE);
vbmeta_offset = avb_be64toh(footer->vbmeta_offset);

Therefore, I add the following in "external/avb/Android.bp"
cc_library_static {
    name: "libavb",
    defaults: [
        "avb_defaults",
        "avb_sources",
    ],
    ...
    target: {
        windows: {
            srcs: ["libavb/avb_sysdeps_posix.c"],
            enabled: true,
        },

But, the following build error will generate.
external/avb/libavb/avb_sysdeps_posix.c:25:10: fatal error: 'endian.h' file not found
#include <endian.h>

Do you have any suggestion?

Thanks.

Patch-set: 1
CC: Gerrit User 1494602 <1494602@85c56323-6fa9-3386-8a01-6480fb634889>