Update patch set 21
Patch Set 21: Verified-1

LogBufferElement.cpp also needs to #include <endian.h>, or the clang build will break:

system/core/logd/LogBufferElement.cpp:79:25: error: use of undeclared identifier 'htole32'
        e->header.tag = htole32(LOGD_LOG_TAG);
                        ^
system/core/logd/LogBufferElement.cpp:81:21: error: use of undeclared identifier 'htole32'
        e->length = htole32(len);
                    ^

Patch-set: 21
Label: Verified=-1