fastboot: Fix variable name collision with interface macro in Windows
This only changes the variable name 'interface' to 'ifc_interface'
becuase the variable name is same as 'interface' macro used in
various Windows headers `#define interface struct`. It was added
in 4e058cac0d1db29824000a24d2dd602885880e50 commit.

This fixes errors like following:

core/fastboot/usb.h:54:19: error: expected identifier before '[' token
   54 |     char interface[256];
      |                   ^
core/fastboot/fastboot.cpp:286:21: error: expected primary-expression before 'struct'
  286 |         std::string interface = info->interface;
      |                     ^~~~~~~~~

Change-Id: I82ac80d806b217700f327486ef342ae062cf1dbe