Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> hi Bowgo,
> 
> The following suggestion is good, but this will cause build errors related to functions in "libavb/avb_sysdeps_posix.c".
> cosnt AvbFooter* footer = reinterpret_cast<const AvbFooter*>(
>         x.data() + buf->sz - AVB_FOOTER_SIZE);
> vbmeta_offset = avb_be64toh(footer->vbmeta_offset);
> 
> Therefore, I add the following in "external/avb/Android.bp"
> cc_library_static {
>     name: "libavb",
>     defaults: [
>         "avb_defaults",
>         "avb_sources",
>     ],
>     ...
>     target: {
>         windows: {
>             srcs: ["libavb/avb_sysdeps_posix.c"],
>             enabled: true,
>         },
> 
> But, the following build error will generate.
> external/avb/libavb/avb_sysdeps_posix.c:25:10: fatal error: 'endian.h' file not found
> #include <endian.h>
> 
> Do you have any suggestion?
> 
> Thanks.

I think that's because <endian.h> isn't available on Windows (we need to build fastboot.exe, too). As we only need one function be64toh(), how about just implement it here?

Then we'll just need libavb headers, where we can add a 'cc_library_headers' in libavb.

Can search 'libbase_headers' as an example:
https://android.googlesource.com/platform/system/core/+/refs/heads/master/base/Android.bp

Thanks enh@ for the pointers!

Patch-set: 1
Reviewer: Gerrit User 1080813 <1080813@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0