Update patch set 4
Patch Set 4: Verified+1

Test results:

NB: Hikey has a failure with properties test because the bootloader fails to set ro.boot.bootreason. All the other tests succeed because pstore is functional and because of all the backup and additional verification/validation done in bootstat/bootstat.cpp.

$ system/core/bootstat/boot_reason_test.sh $H1
INFO: selected test(s): properties ota cold factory_reset hard battery unknown kernel_panic warm thermal_shutdown

[ RUN      ] properties 
ERROR: expected "reboot" got ""
       for Android property ro.boot.bootreason
INFO: ok "reboot,bootloader" for Android property persist.sys.boot.reason
INFO: ok "bootloader" for Android property sys.boot.reason
INFO: properties test duration 1 second
[  FAILED  ] properties 

[ RUN      ] ota 
INFO: expected duration of ota test about 5 minutes or more
      extended by build and flashing times
. . .
checking product...
OKAY [  0.001s]
checking version-bootloader...
OKAY [  0.001s]
sending 'boot' (23078 KB)...
OKAY [  0.773s]
writing 'boot'...
OKAY [  1.525s]
erasing 'system'...
OKAY [  0.003s]
sending sparse 'system' 1/8 (131071 KB)...
OKAY [  4.412s]
writing 'system' 1/8...
OKAY [  8.611s]
sending sparse 'system' 2/8 (129055 KB)...
OKAY [  4.344s]
writing 'system' 2/8...
OKAY [  7.366s]
sending sparse 'system' 3/8 (129545 KB)...
OKAY [  4.330s]
writing 'system' 3/8...
OKAY [  7.090s]
sending sparse 'system' 4/8 (128117 KB)...
OKAY [  4.327s]
writing 'system' 4/8...
OKAY [  7.982s]
sending sparse 'system' 5/8 (128629 KB)...
OKAY [  4.296s]
writing 'system' 5/8...
OKAY [  7.154s]
sending sparse 'system' 6/8 (119983 KB)...
OKAY [  4.028s]
writing 'system' 6/8...
OKAY [  7.113s]
sending sparse 'system' 7/8 (130874 KB)...
OKAY [  4.605s]
writing 'system' 7/8...
OKAY [  7.882s]
sending sparse 'system' 8/8 (102223 KB)...
OKAY [  3.424s]
writing 'system' 8/8...
OKAY [  6.059s]
rebooting...

finished. total time: 95.382s
INFO: ok "reboot,ota" for Android property sys.boot.reason
INFO: ok "reboot,bootloader" for Android property persist.sys.boot.reason
INFO: ota test duration 4:15
[       OK ] ota 

[ RUN      ] cold 
INFO: expected duration of cold test roughly 45 seconds
INFO: ok "cold" for Android property sys.boot.reason
INFO: ok "reboot,cold" for Android property persist.sys.boot.reason
INFO: cold test duration 41 seconds
[       OK ] cold 

[ RUN      ] factory_reset 
INFO: expected duration of factory_reset test roughly 45 seconds
INFO: ok "reboot,factory_reset" for Android property sys.boot.reason
INFO: ok "reboot," for Android property persist.sys.boot.reason
01-01 00:00:37.503  2510  2510 E bootstat: Failed to read /data/misc/bootstat/build_date: No such file or directory
01-01 00:00:37.503  2510  2510 E bootstat: Failed to parse boot time record: /data/misc/bootstat/build_date
INFO: factory_reset test duration 42 seconds
[       OK ] factory_reset 

[ RUN      ] hard 
INFO: expected duration of hard test roughly 45 seconds
INFO: ok "hard" for Android property sys.boot.reason
INFO: ok "reboot,hard" for Android property persist.sys.boot.reason
INFO: hard test duration 42 seconds
[       OK ] hard 

[ RUN      ] battery 
INFO: ok "shutdown,battery" for Android property sys.boot.reason
INFO: ok "reboot,warm" for Android property persist.sys.boot.reason
01-01 00:00:38.098  2510  2510 I bootstat: Battery level at shutdown 2%
INFO: battery test duration 1:25
[       OK ] battery 

[ RUN      ] unknown 
INFO: expected duration of unknown test roughly 45 seconds
INFO: ok "reboot,unknown" for Android property sys.boot.reason
INFO: ok "reboot,unknown" for Android property persist.sys.boot.reason
01-01 00:00:36.898  2509  2509 I bootstat: Unknown boot reason: reboot,unknown
INFO: unknown test duration 40 seconds
[       OK ] unknown 

[ RUN      ] kernel_panic 
INFO: expected duration of kernel_panic test > 2 minutes
INFO: ok "kernel_panic,sysrq" for Android property sys.boot.reason
INFO: ok "kernel_panic,sysrq" for Android property persist.sys.boot.reason
INFO: kernel_panic test duration 46 seconds
[       OK ] kernel_panic 

[ RUN      ] warm 
INFO: expected duration of warm test roughly 45 seconds
INFO: ok "warm" for Android property sys.boot.reason
INFO: ok "reboot,warm" for Android property persist.sys.boot.reason
INFO: warm test duration 43 seconds
[       OK ] warm 

[ RUN      ] thermal_shutdown 
INFO: expected duration of thermal_shutdown test roughly a minute plus
      power on request
WARNING: Please power device back up, waiting ... 
INFO: ok "shutdown,thermal" for Android property sys.boot.reason
INFO: ok "shutdown,thermal" for Android property persist.sys.boot.reason
INFO: thermal_shutdown test duration 47 seconds
[       OK ] thermal_shutdown 

[  PASSED  ] ota cold factory_reset hard battery unknown warm thermal_shutdown
[  FAILED  ] properties kernel_panic

$ system/core/bootstat/boot_reason_test.sh $H1 properties kernel_panic unknown optional_ota optional_factory_reset
INFO: selected test(s): properties kernel_panic unknown optional_ota optional_factory_reset

[ RUN      ] properties 
ERROR: expected "reboot" got ""
       for Android property ro.boot.bootreason
INFO: ok "shutdown,thermal" for Android property persist.sys.boot.reason
INFO: ok "shutdown,thermal" for Android property sys.boot.reason
01-01 00:01:00.379     0     0 I init    : Service 'exec 7 (/system/bin/bootstat --record_boot_complete)' (pid 3176) exited with status 0 waiting took 0.063000 seconds
INFO: properties test duration 1 second
[  FAILED  ] properties 

[ RUN      ] kernel_panic 
INFO: expected duration of kernel_panic test > 2 minutes
INFO: ok "kernel_panic,sysrq" for Android property sys.boot.reason
INFO: ok "kernel_panic,sysrq" for Android property persist.sys.boot.reason
INFO: kernel_panic test duration 47 seconds
[       OK ] kernel_panic 

[ RUN      ] unknown 
INFO: expected duration of unknown test roughly 45 seconds
INFO: ok "reboot,unknown" for Android property sys.boot.reason
INFO: ok "reboot,unknown" for Android property persist.sys.boot.reason
01-01 00:00:37.917  2506  2506 I bootstat: Unknown boot reason: reboot,unknown
INFO: unknown test duration 41 seconds
[       OK ] unknown 

[ RUN      ] optional_ota 
INFO: expected duration of optional_ota test about 45 seconds
INFO: ok "reboot,ota" for Android property sys.boot.reason
INFO: ok "reboot,ota" for Android property persist.sys.boot.reason
INFO: optional_ota test duration 43 seconds
[       OK ] optional_ota 

[ RUN      ] optional_factory_reset 
INFO: expected duration of optional_factory_reset test roughly a minute
. . .                     
erasing 'userdata'...
OKAY [  0.003s]
sending 'userdata' (2140 KB)...
OKAY [  0.077s]
writing 'userdata'...
OKAY [  0.628s]
finished. total time: 0.708s
rebooting...

finished. total time: 0.202s
INFO: ok "reboot,factory_reset" for Android property sys.boot.reason
INFO: ok "" for Android property persist.sys.boot.reason
01-01 00:00:48.229  2601  2601 E bootstat: Failed to read /data/misc/bootstat/last_boot_time_utc: No such file or directory
01-01 00:00:48.229  2601  2601 E bootstat: Failed to parse boot time record: /data/misc/bootstat/last_boot_time_utc
01-01 00:00:48.230  2601  2601 E bootstat: Failed to read /data/misc/bootstat/build_date: No such file or directory
01-01 00:00:48.230  2601  2601 E bootstat: Failed to parse boot time record: /data/misc/bootstat/build_date
01-01 00:00:48.366  2603  2603 E bootstat: Failed to read /data/misc/bootstat/factory_reset: No such file or directory
01-01 00:00:48.366  2603  2603 E bootstat: Failed to parse boot time record: /data/misc/bootstat/factory_reset
INFO: optional_factory_reset test duration 56 seconds
[       OK ] optional_factory_reset 

[  PASSED  ] kernel_panic unknown optional_ota optional_factory_reset
[  FAILED  ] properties

Patch-set: 4
Reviewer: Gerrit User 1032276 <1032276@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1