Update patch set 1
Patch Set 1:

When cherry-picking into master:

system/core/liblog/include_vndk/android/log.h:153:3: error: ISO C restricts enumerator values to range of 'int' (4294967295 is too large) [-Werror,-Wpedantic]
  LOG_ID_INVALID = 0xFFFFFFFF,

Looks like this isn't a viable strategy after all.

I think at this point it's probably best to just leave it as is.  I don't see callers outside of liblog comparing this value to LOG_ID_MAX (which would be problematic if they're updated separately from liblog).  They're all taking this value and passing it back into liblog, so we should be safe as long as liblog does the right thing with it.

The logcat crash on the bug is happening within liblog's android_log_id_to_name(), not logcat itself.

Patch-set: 1
Reviewer: Gerrit User 1064128 <1064128@85c56323-6fa9-3386-8a01-6480fb634889>