Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Presubmit-Ready+1
> > 
> > Since you were asking me about the usability of this, I tried it out.  
> > 
> > Crazily enough, I actually ran into problems with this example.  I didn't realize that I had '{' and '}' in the string and that I would need to escape them.  The compiler didn't catch this either, and the result was _no_ log being printed at all.  It wasn't totally obvious to me why it was wrong until I printed the string section by section and saw the '{' and realized it was the problem.
> 
> interesting. the {{ escaping is ugly too.

Indeed.

> 
> did you try the compile-time check macro? (though that probably won't help as much for stuff like this as it will for actual direct logging where you're already probably using a macro anyway.)

I just tried and it does catch the issue, though with a bit hard to interpret error below.  It looks like it tries to interpret the content with in {} as a named argument, but the compile time checker doesn't support that.  That's unfortunate if true, since it means we can't put this on by default (aka hide it in a LOG or macro), or otherwise we would have to only expose a subset of fmtlib to users.

I needed to make some changes to libbase to get this to build as well, though they were mostly trivial.

external/fmtlib/include/fmt/format.h:2680:27: error: constexpr variable 'invalid_format' must be initialized by a constant expression
  FMT_CONSTEXPR_DECL bool invalid_format =
                          ^
external/fmtlib/include/fmt/core.h:1390:3: note: in instantiation of function template specialization 'fmt::v6::internal::check_format_string<int, unsigned lon
g, unsigned long, str, 0>' requested here
  check_format_string<remove_const_t<remove_reference_t<Args>>...>(format_str);
  ^
external/fmtlib/include/fmt/core.h:1476:18: note: in instantiation of function template specialization 'fmt::v6::internal::make_args_checked<const int &, const
 unsigned long &, const unsigned long &, str, char>' requested here
      {internal::make_args_checked<Args...>(format_str, args...)});
                 ^
system/core/base/include/android-base/result.h:201:34: note: in instantiation of function template specialization 'fmt::v6::format<str, const int &, const unsi
gned long &, const unsigned long &, char>' requested here
  return Error(true, errno, fmt::format(fmt, args...));
                                 ^
system/core/init/service_utils.cpp:252:18: note: in instantiation of function template specialization 'android::base::ErrnoErrorf<str, int, unsigned long, unsi
gned long>' requested here
          return ErrnoErrorf(FMT_STRING("setrlimit({}, {rlim_cur={}, rlim_max={}}) failed"), rlimit.first,
                 ^
external/fmtlib/include/fmt/core.h:532:19: note: non-constexpr function 'on_error' cannot be used in a constant expression
    ErrorHandler::on_error(message);
                  ^
external/fmtlib/include/fmt/format.h:2650:14: note: in call to '&checker.context_->on_error(&"compile-time checks don't support named arguments"[0])'
    context_.on_error(message);
             ^
external/fmtlib/include/fmt/format.h:2639:5: note: in call to '&checker->on_error(&"compile-time checks don't support named arguments"[0])'
    on_error("compile-time checks don't support named arguments");
    ^

...

Patch-set: 1
Reviewer: Gerrit User 1064128 <1064128@85c56323-6fa9-3386-8a01-6480fb634889>