logwrapper: fix missing include
Use of ECHILD with no definitive errno.h inclusion.

When mmm -B system/core/logwrapper this error surfaces:
system/core/logwrapper/logwrapper.c:97:19: error: 'ECHILD' undeclared (first use in this function)

Change-Id: I5552acd928d17fc62192217a30ff2e4fab0b1936