Update patch set 6
Patch Set 6:

This CL is causing the following breakage "git_master/sdk_gphone_x86-sdk_addon_mac @ 5223607"

make -j30 PRODUCT-sdk_gphone_x86-sdk_addon showcommands dist DIST_DIR=/buildbot/dist_dirs/git_master-mac-sdk_gphone_x86-sdk_addon/5223607 sdk_repo emulator_tests
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: system/core/fs_mgr/libfs_avb/Android.bp:17:1: module "libfs_avb" variant "darwin_x86_64_static": depends on disabled module "libavb"
ninja: build stopped: subcommand failed.
18:27:01 soong bootstrap failed with: exit status 1
make: *** [run_soong_ui] Error 1
Return Code: 2

Are there dependent CLs that are pending to be merged ?

Patch-set: 6
CC: Gerrit User 1042384 <1042384@85c56323-6fa9-3386-8a01-6480fb634889>