Update patch set 1
Patch Set 1:

Hi,
Just to provide more contexts.

We're adding another CL that will use some of htonl(), ntohl(), htons(), ntohs() in fastboot.cpp.

Without this CL, it will have the following compile error, because fastboot indirectly includes <winsock2.h>:


In file included from system/core/fastboot/fastboot.cpp:74:                                                                                                                  
In file included from system/core/fastboot/tcp.h:36:                                                                                                                         
In file included from system/core/fastboot/socket.h:42:
In file included from system/core/libcutils/include/cutils/sockets.h:28:
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/winsock2.h:982:37: error: functions that differ only in their return type cannot be overloade$
  WINSOCK_API_LINKAGE u_long WSAAPI htonl(u_long hostlong);
                                    ^
system/core/base/include/android-base/endian.h:57:18: note: expanded from macro 'htonl'                                                                                     
#define htonl(x) __builtin_bswap32(x)
                 ^
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/winsock2.h:982:37: note: previous implicit declaration is here                               
system/core/base/include/android-base/endian.h:57:18: note: expanded from macro 'htonl'                                                                                     
#define htonl(x) __builtin_bswap32(x)
                 ^
In file included from system/core/fastboot/fastboot.cpp:74:
In file included from system/core/fastboot/tcp.h:36:
In file included from system/core/fastboot/socket.h:42:
In file included from system/core/libcutils/include/cutils/sockets.h:28:
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/winsock2.h:989:37: error: functions that differ only in their return type cannot be overloade$
  WINSOCK_API_LINKAGE u_long WSAAPI ntohl(u_long netlong);
                                    ^
system/core/base/include/android-base/endian.h:59:18: note: expanded from macro 'ntohl'                                                                                     
#define ntohl(x) __builtin_bswap32(x)
                 ^
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/winsock2.h:982:37: note: previous implicit declaration is here                               
  WINSOCK_API_LINKAGE u_long WSAAPI htonl(u_long hostlong);
                                    ^
system/core/base/include/android-base/endian.h:57:18: note: expanded from macro 'htonl'                                                                                     
#define htonl(x) __builtin_bswap32(x)
                 ^
2 errors generated.
23:12:59 ninja failed with: exit status 1

Patch-set: 1
Reviewer: Gerrit User 1080813 <1080813@85c56323-6fa9-3386-8a01-6480fb634889>