Update patch set 3
Patch Set 3:

This CL has broken the mac build (which is super flaky, but this looks like a genuine breakage):

system/core/fastboot/usb_osx.cpp:513:35: error: use of undeclared identifier 'USB_TRANSACTION_TIMEOUT'
USB_TRANSACTION_TIMEOUT, USB_TRANSACTION_TIMEOUT);
^

I'll prepare a revert?

Patch-set: 3
CC: Gerrit User 1103203 <1103203@85c56323-6fa9-3386-8a01-6480fb634889>