Fix up Debug.h.
The main purpose of this is to change 'class' to 'struct' in one instance, to
avoid the following compilation error:

error: class template 'CompileTimeAssert' was previously declared as a struct
template [-Werror,-Wmismatched-tags]

system/core/include/utils/Debug.h:30:14: note: expanded from macro
'COMPILE_TIME_ASSERT'
    template class CompileTimeAssert< (_exp) >;
             ^
system/core/include/utils/Debug.h:27:23: note: previous use is here
template<bool> struct CompileTimeAssert;
                      ^

In the process, take the opportunity to also:
+ Remove unused includes.
+ Remove the __cplusplus guards. Everything in this file is C++, including
  "namespace" and "template". No C code includes this file (indeed if it had, it
  would've broken because the previous guards didn't guard all the C++ stuff).
+ Move the macros outside the namespace, and make them refer to the explicitly
  namespace-qualified type names. This is so clients don't have to be forced to
  use the macro only within the 'android' namespace.
+ Do other cosmetic changes (fix typo, whitespace, unnecessary semicolon, etc).

Change-Id: I63c60c69243a8d4441c666d326ba05f5134a277f