libutils/libcutils: make host more like device
Having shared host libraries allows libraries depending on these to use
'shared_libs' for these. This simplifies configurations since these
libraries don't have to specify 'shared_libs' on all non-host targets.

Bug: 124524556
Test: wip
out/soong/.intermediates/system/core/libcutils/libcutils/windows_x86_static/obj/system/core/libcutils/socket_inaddr_any_server_windows.o: In function `socket_inaddr_any_server':
system/core/libcutils/socket_inaddr_any_server_windows.cpp:42: undefined reference to `_imp__socket@12'
system/core/libcutils/socket_inaddr_any_server_windows.cpp:53: undefined reference to `_imp__setsockopt@20'

Change-Id: I09fb4a4fb66ea0a87cb76b1e6f400c537a11f082