Update patch set 2
Patch Set 2: Verified+1

optional_factory_reset failure is a KI for Hikey960. fastboot can not wipe userdata:

$ ./system/core/bootstat/boot_reason_test.sh $H2 all
INFO: selected test(s): properties ota optional_ota cold factory_reset optional_factory_reset hard battery optional_battery optional_battery_thermal unknown kernel_panic warm thermal_shutdown userrequested_shutdown shell_reboot adb_reboot Its_Just_So_Hard_reboot

[ RUN      ] properties 
INFO: ok "reboot,its_just_so_hard" for Android property ro.boot.bootreason
INFO: ok "reboot,its_just_so_hard" for Android property persist.sys.boot.reason
INFO: ok "reboot,its_just_so_hard" for Android property sys.boot.reason
01-01 01:06:35.236  2780  2780 I bootstat: Unknown boot reason: reboot,its_just_so_hard
[       OK ] properties 

[ RUN      ] ota 
INFO: expected duration of ota test about 5 minutes or more
      extended by build and flashing times
. . .
INFO: ok "\(reboot,ota\|bootloader\)"(="reboot,ota") for Android property sys.boot.reason
INFO: ok "bootloader" for Android property persist.sys.boot.reason
INFO: ota test duration 3:06
[       OK ] ota 

[ RUN      ] optional_ota 
INFO: optional_ota requires userdebug build
INFO: expected duration of optional_ota test about 45 seconds
INFO: ok "reboot,ota" for Android property sys.boot.reason
INFO: ok "reboot,ota" for Android property persist.sys.boot.reason
INFO: optional_ota test duration 22 seconds
[       OK ] optional_ota 

[ RUN      ] cold 
INFO: expected duration of cold test roughly 45 seconds
INFO: ok "cold" for Android property sys.boot.reason
INFO: ok "cold" for Android property persist.sys.boot.reason
INFO: cold test duration 22 seconds
[       OK ] cold 

[ RUN      ] factory_reset 
INFO: factory_reset requires userdebug build
INFO: expected duration of factory_reset test roughly 45 seconds
INFO: ok "reboot,factory_reset" for Android property sys.boot.reason
INFO: ok "reboot,.*"(="reboot,adb") for Android property persist.sys.boot.reason
INFO: factory_reset test duration 23 seconds
[       OK ] factory_reset 

[ RUN      ] optional_factory_reset 
INFO: expected duration of optional_factory_reset test roughly a minute
< waiting for 8009521471000000 >
Formatting is not supported for file system with type '0.5'.
rebooting...

finished. total time: 0.119s
ERROR: expected "reboot,factory_reset" got "bootloader"
       for Android property sys.boot.reason
ERROR: expected "" got "bootloader"
       for Android property persist.sys.boot.reason
INFO: optional_factory_reset test duration 26 seconds
[  FAILED  ] optional_factory_reset 

[ RUN      ] hard 
INFO: expected duration of hard test roughly 45 seconds
INFO: ok "hard" for Android property sys.boot.reason
INFO: ok "hard" for Android property persist.sys.boot.reason
INFO: hard test duration 23 seconds
[       OK ] hard 

[ RUN      ] battery 
INFO: battery requires userdebug build
INFO: expected duration of battery test roughly two minutes
WARNING: battery requires functional pstore
ERROR: expected "shutdown,battery" got "cold"
       for Android property sys.boot.reason
INFO: ok "cold" for Android property persist.sys.boot.reason
01-01 01:15:34.786  2770  2770 I bootstat: Canonical boot reason: cold
ERROR: battery requires functional pstore, skipping FAILURE
INFO: battery test duration 47 seconds
[       OK ] battery 

[ RUN      ] optional_battery 
INFO: expected duration of optional_battery test roughly a minute plus
      power on request
WARNING: Please power device back up, waiting ... rebooting...

finished. total time: 0.219s

INFO: ok "shutdown,battery" for Android property sys.boot.reason
INFO: ok "shutdown,battery" for Android property persist.sys.boot.reason
INFO: optional_battery test duration 32 seconds
[       OK ] optional_battery 

[ RUN      ] optional_battery_thermal 
INFO: expected duration of optional_battery_thermal test roughly a minute plus
      power on request
WARNING: Please power device back up, waiting ... rebooting...

finished. total time: 0.219s

INFO: ok "shutdown,thermal,battery" for Android property sys.boot.reason
INFO: ok "shutdown,thermal,battery" for Android property persist.sys.boot.reason
01-01 01:16:39.415  2781  2781 I bootstat: Unknown boot reason: shutdown,thermal,battery
INFO: optional_battery_thermal test duration 33 seconds
[       OK ] optional_battery_thermal 

[ RUN      ] unknown 
INFO: expected duration of unknown test roughly 45 seconds
INFO: ok "reboot,unknown" for Android property sys.boot.reason
INFO: ok "reboot,unknown" for Android property persist.sys.boot.reason
01-01 01:17:03.094  2775  2775 I bootstat: Unknown boot reason: reboot,unknown
INFO: unknown test duration 23 seconds
[       OK ] unknown 

[ RUN      ] kernel_panic 
INFO: kernel_panic requires userdebug build
INFO: expected duration of kernel_panic test > 2 minutes
WARNING: kernel_panic requires functional pstore
rebooting...

finished. total time: 0.119s
ERROR: expected "\(kernel_panic,sysrq\|kernel_panic\)" got "reboot,unknown"
       for Android property sys.boot.reason
ERROR: expected "\(kernel_panic,sysrq\|kernel_panic\)" got "reboot,unknown"
       for Android property persist.sys.boot.reason
01-01 01:17:33.078  2783  2783 I bootstat: Canonical boot reason: reboot,unknown
01-01 01:17:33.078  2783  2783 I bootstat: Unknown boot reason: reboot,unknown
ERROR: kernel_panic requires functional pstore, skipping FAILURE
INFO: kernel_panic test duration 30 seconds
[       OK ] kernel_panic 

[ RUN      ] warm 
INFO: expected duration of warm test roughly 45 seconds
INFO: ok "warm" for Android property sys.boot.reason
INFO: ok "warm" for Android property persist.sys.boot.reason
INFO: warm test duration 22 seconds
[       OK ] warm 

[ RUN      ] thermal_shutdown 
INFO: expected duration of thermal_shutdown test roughly a minute plus
      power on request
WARNING: Please power device back up, waiting ... rebooting...

finished. total time: 0.218s

INFO: ok "shutdown,thermal" for Android property sys.boot.reason
INFO: ok "shutdown,thermal" for Android property persist.sys.boot.reason
INFO: thermal_shutdown test duration 29 seconds
[       OK ] thermal_shutdown 

[ RUN      ] userrequested_shutdown 
INFO: expected duration of userrequested_shutdown test roughly a minute plus
      power on request
WARNING: Please power device back up, waiting ... rebooting...

finished. total time: 0.068s

INFO: ok "shutdown,userrequested" for Android property sys.boot.reason
INFO: ok "shutdown,userrequested" for Android property persist.sys.boot.reason
INFO: userrequested_shutdown test duration 33 seconds
[       OK ] userrequested_shutdown 

[ RUN      ] shell_reboot 
INFO: expected duration of shell_reboot test roughly 45 seconds
INFO: ok "reboot,shell" for Android property sys.boot.reason
INFO: ok "reboot,shell" for Android property persist.sys.boot.reason
INFO: shell_reboot test duration 23 seconds
[       OK ] shell_reboot 

[ RUN      ] adb_reboot 
INFO: expected duration of adb_reboot test roughly 45 seconds
INFO: ok "reboot,adb" for Android property sys.boot.reason
INFO: ok "reboot,adb" for Android property persist.sys.boot.reason
INFO: adb_reboot test duration 23 seconds
[       OK ] adb_reboot 

[ RUN      ] Its_Just_So_Hard_reboot 
INFO: Its_Just_So_Hard_reboot requires userdebug build
INFO: expected duration of Its_Just_So_Hard_reboot test roughly 45 seconds
INFO: ok "reboot,its_just_so_hard" for Android property sys.boot.reason
INFO: ok "reboot,Its Just So Hard" for Android property persist.sys.boot.reason
INFO: ok "reboot,its_just_so_hard" for Android property persist.sys.boot.reason
01-01 01:20:06.389  2775  2775 I bootstat: Unknown boot reason: reboot,its_just_so_hard
INFO: Its_Just_So_Hard_reboot test duration 23 seconds
[       OK ] Its_Just_So_Hard_reboot 

[  PASSED  ] properties ota optional_ota cold factory_reset hard battery optional_battery optional_battery_thermal unknown kernel_panic warm thermal_shutdown userrequested_shutdown shell_reboot adb_reboot Its_Just_So_Hard_reboot
[  FAILED  ] optional_factory_reset

Patch-set: 2
Reviewer: Gerrit User 1032276 <1032276@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1