Revert "Incremental installations in adb, client/host side."
This reverts commit 96ff54bf347378025d1e55bf0e6364835005d585.

Reason for revert: breaks git_master-without-vendor on sdk_mac

system/core/adb/client/incremental.cpp:30:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~

Change-Id: I999bb745b788cabe036b94f41d745be35278f3d8