Update patch set 8
Patch Set 8:

> > out/host/windows-x86/obj/STATIC_LIBRARIES/libbase_intermediates/libbase.a(logging.o):
 > > In function `ZN7android4base12StderrLoggerENS0_5LogIdENS0_11LogSeverityEPKcS4_jS4_':
 > > system/core/base/logging.cpp:161: undefined reference to `gettid'
 > 
 > Hmm, I don't see any problem on my end and I don't think I touched
 > that stuff. I just did a clean build (m clean, then m
 > host_cross_adb) and it worked fine. gettid() should be in
 > libcutils/threads.c:
 > 
 > user@ubuntu:~/a/out/host/windows-x86$ grep -rl gettid *
 > bin/adb.exe
 > obj/EXECUTABLES/adb_intermediates/adb.exe
 > obj/STATIC_LIBRARIES/libbase_intermediates/logging.o
 > obj/STATIC_LIBRARIES/libbase_intermediates/libbase.a
 > obj/STATIC_LIBRARIES/libcutils_intermediates/threads.o
 > obj/STATIC_LIBRARIES/libcutils_intermediates/libcutils.a
 > 
 > Thoughts?


Just did a fresh sync and downloaded this CL, I get the same error as enh with `mm` and `mma` builds in system/core, but the full `m` build works. Maybe a missing dependency that the full build happens to pick up elsewhere?

Patch-set: 8
Reviewer: Gerrit User 1078119 <1078119@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0